apiVersion: v1
kind: Service
metadata:
  name: user-mysql-service
spec:
  selector:
    name: user-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: user-mysql-tcp